apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-storage-claim
  labels:
    app: goals-frontend
spec:
  accessModes:
    - ReadWriteMany
    #- ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
