#apiVersion: apps/v1 # para versiones anteriores a 1.9.0 use apps/v1beta2 o extensions/v1beta1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goals-backend-deployment
  labels:
    app: goals-backend
spec:
  replicas: 1
  #selector:
  #  matchLabels:
  #    app: goals-backend
  template:
    metadata:
      labels:
        app: goals-backend
        role: edge-service
        tier: backend
    spec:
      containers:
      - name: goals-backend
        image: nagarciah/goals-backend:latest
        ports:
        - containerPort: 8080
