apiVersion: v1
kind: Service
metadata:
  name: goals-backend-service
  labels:
    name: goals-backend-service
    app: goals-backend
spec:
  ports:
  - port: 80
    targetPort: 8080 #Puerto expuesto por el contenedor
  selector:
    app: goals-backend