apiVersion: v1
kind: Service
metadata:
  name: goals-frontend-service
  labels:
    name: goals-frontend-service
spec:
  type: NodePort
  ports:
  - port: 8080 #Puerto expuesto por el contenedor
    nodePort: 30001
  sessionAffinity: ClientIP
  selector:
    app: goals-frontend # TODO Selector del pod o del deployment?