apiVersion: v1 
kind: Endpoints 
metadata: 
  name: nfs-external-service 
  labels:
    app: goals-frontend
subsets: 
- addresses: 
  - ip: 10.128.0.5
  #- ip: 35.226.83.162
  ports: 
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      protocol: TCP