apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: goals-frontend
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  nfs:
    path: "/var/nfsshare"
    server:  10.128.0.5 #FIX Se debe obtener la IP del service, no sirve nombre del servicio
#    readOnly: false
